<?php
$systemTitle = "Validaci&oacute;n de Facturas Electr&oacute;nicas del Corporativo";
$resultMessage = "";
$resultTitle = "AVISO";
$errorMessage = "";
$errorTitle = "ERROR";
date_default_timezone_set("Etc/GMT+6");
//setlocale(LC_CTYPE,"Spanish_Mexico.UTF-8", "Spanish_Mexican.UTF-8", "es_MX.UTF-8", "Spanish_Mexico.utf8", "Spanish_Mexican.utf8", "es_MX.utf8", "Spanish_Mexico", "Spanish_Mexican", "es_MX", "spanish", "Spanish_Spain.1252");
$mylocale = setlocale(LC_TIME, "Spanish_Mexico.UTF-8", "Spanish_Mexican.UTF-8", "es_MX.UTF-8", "Spanish_Mexico.utf8", "Spanish_Mexican.utf8", "es_MX.utf8", "Spanish_Mexico", "Spanish_Mexican", "es_MX", "spanish", "Spanish_Spain.1252");
const MENSAJE_NAVIDAD2024PM="<P>Estimados Proveedores:</p><p>Agradecemos su compa&ntilde;&iacute;a un a&ntilde;o m&aacute;s y les deseamos salud y prosperidad.</p><p>Les informamos que por motivo del cierre fiscal recibiremos sus facturas de este a&ntilde;o hasta el d&iacute;a <u class='importantValue'>19 de diciembre del 2024</u>.</p><p>Les solicitamos que nuestros pedidos sean atendidos, facturados e ingresados al portal a m&aacute;s tardar en la fecha l&iacute;mite.</p><p>Los pedidos que no hayan subido al portal antes de esta fecha, deber&aacute;n ser facturados hasta el 2025.</p><p>Les deseamos una muy Feliz Navidad 2024 y Pr&oacute;spero A&ntilde;o Nuevo 2025.</p>";
const MENSAJE_NAVIDAD2024PF="<P>Estimados Proveedores:</p><p>Agradecemos su compa&ntilde;&iacute;a un a&ntilde;o m&aacute;s y les deseamos salud y prosperidad.</p><p>Les informamos que por motivo del cierre fiscal recibiremos sus facturas de este a&ntilde;o hasta el d&iacute;a <u class='importantValue'>09 de diciembre del 2024</u>.</p><p>Les solicitamos que nuestros pedidos sean atendidos, facturados e ingresados al portal a m&aacute;s tardar en la fecha l&iacute;mite.</p><p>Los pedidos que no hayan subido al portal antes de esta fecha, deber&aacute;n ser facturados hasta el 2025.</p><p>Les deseamos una muy Feliz Navidad 2024 y Pr&oacute;spero A&ntilde;o Nuevo 2025.</p>";
const MENSAJE_NAVIDAD2023="<P>Estimados Proveedores:</p><p>Agradecemos su compa&ntilde;&iacute;a un a&ntilde;o m&aacute;s y les deseamos salud y prosperidad.</p><p>Les informamos que por motivo del cierre fiscal recibiremos sus facturas de este a&ntilde;o hasta el d&iacute;a <u class='importantValue'>19 de diciembre del 2023</u>.</p><p>Les solicitamos que nuestros pedidos sean atendidos, facturados e ingresados al portal a m&aacute;s tardar en la fecha l&iacute;mite.</p><p>Los pedidos que no hayan subido al portal antes de esta fecha, deber&aacute;n ser facturados hasta el 2024.</p><p>Les deseamos una muy Feliz Navidad 2023 y Pr&oacute;spero A&ntilde;o Nuevo 2024.</p>";
const MENSAJE_NAVIDAD2022="<P>Estimados Proveedores:</p><p>Agradecemos su compa&ntilde;&iacute;a un a&ntilde;o m&aacute;s y les deseamos salud y prosperidad.</p><p>Les informamos que por motivo del cierre fiscal recibiremos sus facturas de este a&ntilde;o hasta el d&iacute;a <u class='importantValue'>19 de diciembre del 2022</u>.</p><p>Les solicitamos que nuestros pedidos sean atendidos, facturados e ingresados al portal a m&aacute;s tardar en la fecha l&iacute;mite.</p><p>Los pedidos que no hayan subido al portal antes de esta fecha, deber&aacute;n ser facturados hasta el 2023.</p><p>Les deseamos una muy Feliz Navidad 2022 y Pr&oacute;spero A&ntilde;o Nuevo 2023.</p>";
const MENSAJE_NAVIDAD2021="<p>Estimados Proveedores:</p><p>Agradecemos su compañía un año más y les deseamos salud y prosperidad</p><p>Les informamos que por motivo del cierre fiscal de este año recibiremos sus facturas hasta el día <u class='importantValue'>28 de diciembre del 2021</u>.</p><p>Les solicitamos que nuestros pedidos de este año sean atendidos, facturados e ingresados al portal a más tardar en la fecha límite.</p><p>Los pedidos posteriores a esta fecha o que no hayan subido al portal deberán ser facturados con fecha de Enero del 2022.</p><p>Les deseamos una muy feliz Navidad y un próspero año nuevo 2022.</p>";
const MENSAJE_NAVIDAD2019="<P>Estimados Proveedores y Socios comerciales:</p><p>Ha sido un placer para nosotros contar con su servicio durante este a&ntilde;o y por esta raz&oacute;n les expresamos nuestro m&aacute;s sincero agradecimiento.</p><p>Les informamos que por motivo del cierre fiscal de este a&ntilde;o recibiremos sus facturas con fecha del 2019 hasta el dia 31 de diciembre del 2019.</p><p>A partir del 1&deg; de enero del 2020 no se recibir&aacute;n facturas del a&ntilde;o 2019 en este portal.</p><p>Pedidos posteriores a esta fecha o que no hayan subido al portal por alguna situaci&oacute;n deber&aacute;n ser facturados con fecha de Enero del 2020.</p><p>Nos despedimos de ustedes no sin antes desearles una vez m&aacute;s Feliz Navidad y Pr&oacute;spero A&ntilde;o Nuevo 2020.</p>";
const MENSAJE_NAVIDAD2017="<p>Estimados Proveedores y Socios comerciales:</p><p>Ha sido un placer para nosotros contar con su servicio durante este año y por esta razón les expresamos nuestro más sincero agradecimiento.</p><p>Así mismo les informamos que por motivo del cierre fiscal de este año y las fiestas decembrinas recibiremos sus facturas hasta el dia <u class='importantValue'>22 de diciembre del 2017</u>.</p><p>Los pedidos enviados a ustedes antes de la fecha mencionada deberán ser facturados y subidos al portal hasta la fecha límite.</p><p>Pedidos posteriores a esta fecha o que no hayan subido al portal por alguna situación deberán ser facturados con fecha de Enero del 2018.</p><p>Les recordamos que a partir del 1&deg; de enero del 2018, la única versión válida será la 3.3.</p><p>Nos despedimos de ustedes no sin antes desearles una vez más una feliz Navidad y un próspero año nuevo 2018.</p>";
const MENSAJE_NAVIDAD2016="<p>Estimados Proveedores y Socios comerciales:</p><p>Ha sido un placer para nosotros contar con su servicio durante este año y por esta razón les expresamos nuestro más sincero agradecimiento.</p><p>Así mismo les informamos que por motivo del cierre fiscal de este año y las fiestas decembrinas recibiremos sus facturas hasta el dia 23 de diciembre del 2016.</p><p>Los pedidos enviados a ustedes antes de la fecha mencionada deberán ser facturados y subidos al portal hasta la fecha límite.</p><p>Pedidos posteriores a esta fecha o que no hayan subido al portal por alguna situación deberán ser facturados con fecha de Enero del 2017.</p><p>Nos despedimos de ustedes no sin antes desearles una vez más una feliz Navidad y un próspero año nuevo 2017.</p>";

const MENSAJE_VERSION33="<p>Estimados Proveedores y Socios comerciales:</p><p>Les informamos que el portal ya permite dar de alta facturas VERSIÓN 3.3.</p><p>Así mismo les recordamos que a partir del 1&deg; de diciembre, la única versión válida será la 3.3.</p>";
const MENSAJE_FINV33_0="<p class='fontRelevant margin20 centered'>Por comunicado oficial del SAT el último día que se recibirán comprobantes fiscales con versión 3.3 será el 31 de marzo 2023. A partir del 1° de abril 2023 sólamente se podrán subir CFDI v4.0.</p><p class='fontRelevant margin20 centered'>Agradecemos su comprensión y dedicación.</p>";
const MENSAJE_FINV33="<p>Estimados Proveedores y Socios comerciales:</p><p>Por comunicado oficial del SAT el último día que se recibirán comprobantes fiscales con versión 3.3 será el 31 de marzo 2023. A partir del 1° de abril 2023 sólamente se podrán subir CFDI v4.0. Agradecemos su comprensión y dedicación.</p>";
const MENSAJE_VERSION40_0="<p class='fontRelevant margin20 centered'>Por comunicado oficial del SAT el 31 de marzo 2023 fue el último día que se recibieron comprobantes fiscales con versión 3.3.<BR>Desde el 1° de abril 2023 sólamente son válidos los CFDI v4.0.<BR>Agradecemos su comprensión y dedicación.</p>";
const MENSAJE_VERSION40="<p>Estimados Proveedores y Socios comerciales:</p><p>Por comunicado oficial del SAT el 31 de marzo 2023 fue el último día que se recibieron comprobantes fiscales con versión 3.3.</p><p>Desde el 1° de abril 2023 sólamente son válidos los CFDI v4.0.</p><p>Agradecemos su comprensión y dedicación.</p>";

const MENSAJE_RECIBOSPAGO="<p>Estimados Proveedores:</p><p>Se les informa que los <b class='highMsg'>Datos Bancarios</b> para generar el <b class='highMsg'>Recibo de Pago</b> se los proporcionará el <b class='highMsg'>Personal del Área de Compras</b> de cada empresa.</p><p>Usted deberá subir el <b class='highMsg underDash' title='Recibo Electrónico de Pago'>R.E.P.</b> en este mismo portal, recordando que para entregarlos cuenta con <b class='highMsg'>10 días naturales</b> del mes próximo a la fecha de <b>recibir el pago</b> o se suspenderán sus pagos posteriores.</p><p>Recuerde que con el <b class='highMsg underDash' title='Recibo Electrónico de Pago'>R.E.P.</b> está confirmando que ha recibido el pago de las facturas incluidas.</p>";
const MENSAJE_FALLOSAT="<p>Estimados Proveedores:</p><p>Por el momento no tenemos <b class='highMsg'>Alta de Facturas y Pagos</b> en el Portal debido a que el SAT no responde al realizar la validaci&oacute;n requerida.</p><p>Mientras esto se resuelve le pedimos que envíe por correo electrónico al área de compras correspondiente, los archivos XML y PDF de sus facturas, notas y recibos de pago.</p><p>Recuerde que la fecha límite para enviarnos sus <b class='highMsg underDash' title='Recibo Electrónico de Pago'>R.E.P.</b> es el d&eacute;cimo d&iacute;a del mes siguiente en que ha recibido el pago por las facturas incluidas.</p>"; // 2018/11/05
const MENSAJE_RECIBOSPAGO2="<p>Estimados Proveedores:</p><p>La conexi&oacute;n al SAT se ha reestablecido y ya puede realizar el Alta de sus Facturas y Pagos.</p><p>Les recordamos que la fecha límite para realizar el alta de sus <b class='highMsg underDash' title='Recibo Electrónico de Pago'>R.E.P.</b> es el d&eacute;cimo d&iacute;a del mes siguiente en que ha recibido el pago por las facturas incluidas.</p>";
//2019/03/22
const MENSAJE_RECIBOSPAGO3="<p>Estimados Proveedores:</p><p>Les recordamos que la fecha límite para realizar el alta de sus <b class='highMsg underDash' title='Recibo Electrónico de Pago'>R.E.P.</b> es el d&eacute;cimo d&iacute;a del mes siguiente en que ha recibido el pago por las facturas incluidas.</p>";
const MENSAJE_LIMITE_MES_INTERNO="<P class=\"padhtt boldValue nomargin\">Mensaje Interno para Empleados con Alta de Facturas:</P><P>Los proveedores no pueden realizar alta de facturas de meses anteriores, además se les deshabilitará la opción de <B>Alta De Facturas</B> durante el último día hábil de cada mes después de las 16 hrs.</P><P>Los usuarios internos no tendrán estas limitantes para casos de emergencia, pero en general se deberá pedir al proveedor que refacture.</P><P><B>NUEVO AVISO:</B> No se aceptarán facturas con usoCFDI='P01'.</P>";
const MENSAJE_LIMITE_MES="<P>Estimados Proveedores:</P><P>Les recordamos que el último día hábil de cada mes, deberá subir sus facturas antes de las 16 hrs.</P><P>Les solicitamos que ingresen sus facturas a tiempo de otra forma será necesario refacturar.</P><P>Así mismo les informamos que ninguna factura puede tener <code>usoCFDI</code> '<B>P01</B>'.</P><P>Las facturas con <code>usoCFDI</code> '<B>P01</B>' no podrán ser aceptadas en este portal.</P>";
const SUBMENSAJE_ANTEPENULTIMO_DIA_MES="<P>Le recordamos que el último día del mes deberá subir sus facturas antes de las 16 hrs.</P><P>Le solicitamos que ingrese sus facturas a tiempo de otra forma será necesario refacturar.</P>";
const SUBMENSAJE_PENULTIMO_DIA_MES="<P>Le recordamos que mañana deberá subir sus facturas antes de las 16 hrs.</P><P>Le solicitamos que ingrese sus facturas a tiempo de otra forma será necesario refacturar.</P>";
const SUBMENSAJE_ULTIMO_DIA_MES="<P>Le recordamos que hoy deberá subir sus facturas antes de las 16 hrs.</P><P>Le solicitamos que ingrese sus facturas a tiempo de otra forma será necesario refacturar.</P>";
const MENSAJE_ACTUALIZAR1="<P class='fontRelevant margin20 centered'>Solicitamos que actualice sus datos, son necesarios para poder procesar sus facturas.</P>";
const MENSAJE_ACTUALIZAR2="<P class='fontRelevant margin20 centered'>Encontramos inconsistencias entre su estado de cuenta y los datos bancarios proporcionados.<BR>Solicitamos que el documento corresponda a los datos bancarios ingresados.</P>";
const MENSAJE_ACTUALIZAR3="<P class='fontRelevant margin20 centered'>Encontramos inconsistencias en su documento de Opini&oacute;n de Cumplimiento.<BR>Solicitamos que reemplace el documento por uno v&aacute;lido y actualizado.</P>";
const MENSAJE_ACTUALIZAR4="<P class='fontRelevant margin20 centered'>Solicitamos ingrese su documento de Opini&oacute;n de Cumplimiento de acuerdo a lo previsto por el SAT.<BR>EN CASO DE NO SUBIRLO, SE DETENDRÁN LOS PAGOS A PARTIR DE LA PRÓXIMA SEMANA.</P>";
const MENSAJE_ACTUALIZAR5="<P class='fontRelevant margin20 centered'>Su documento de Opini&oacute;n de Cumplimiento ha vencido.<BR>Requerimos que reemplace el documento por uno actualizado.<BR>EN CASO DE NO SUBIRLO, SE DETENDRÁN LOS PAGOS A PARTIR DE LA PRÓXIMA SEMANA.</P>";
const MENSAJE_COMPLEMENTOS="<P class='fontRelevant margin20 centered'>Sus pagos están detenidos hasta que entregue<br>los Complementos de Pago faltantes o sean<br>validados. Si están rechazados deberá volver<br>a generarlos, consulte a su agente de compras.</P>";
const MENSAJE_CONSITFIS="<P class='fontRelevant margin20 centered'>Le recordamos que puede consultar las &#34;<B>Constancias de Situaci&oacute;n Fiscal</B>&#34; en la opci&oacute;n del men&uacute; <B><U>CONSTANCIA SIT. FISCAL</U></B></P>";
const AVISO_GENERAL="";
const AVISO_GENERAL_PF=""; //"<p class=\"fontRelevant margin20 centered\">Les informamos que por motivo del cierre fiscal recibiremos sus facturas de este a&ntilde;o hasta el d&iacute;a <u class='importantValue'>09 de diciembre del 2024</u>. Los pedidos que no hayan subido al portal antes de esta fecha, deber&aacute;n ser facturados hasta el 2025. Les deseamos una muy Feliz Navidad 2024 y Pr&oacute;spero A&ntilde;o Nuevo 2025.</p>";
const AVISO_GENERAL_PM=""; //"<p class=\"fontRelevant margin20 centered\">Les informamos que por motivo del cierre fiscal recibiremos sus facturas de este a&ntilde;o hasta el d&iacute;a <u class='importantValue'>19 de diciembre del 2024</u>. Los pedidos que no hayan subido al portal antes de esta fecha, deber&aacute;n ser facturados hasta el 2025. Les deseamos una muy Feliz Navidad 2024 y Pr&oacute;spero A&ntilde;o Nuevo 2025.</p>";
const AVISO_GENERAL_PROVEEDOR="<P class='fontRelevant margin20 centered'>Nuevamente le informamos que puede consultar las<br>&#34;<B>Constancias de Situaci&oacute;n Fiscal</B>&#34; de nuestras empresas<br>en la opci&oacute;n del men&uacute; lateral <B><U>CONSTANCIA SIT. FISCAL</U></B></P>";
// MENSAJE: Noticia util, conocimiento relevante genérico. Se muestra sólo una vez por usuario: Actualización, Agradecimiento
const MENSAJE=["GENERAL"=>"","COMPRAS"=>"","PROVEEDOR"=>""];
// AVISO: Explicación de un cambio importante para el usuario. Se muestra 3 veces por usuario: 
const AVISO=["GENERAL"=>"","COMPRAS"=>"","PROVEEDOR"=>"Nuevamente le informamos que puede consultar las<br>&#34;<B>Constancias de Situaci&oacute;n Fiscal</B>&#34; de nuestras empresas<br>en la opci&oacute;n del men&uacute; lateral <B><U>CONSTANCIA SIT. FISCAL</U></B>"];
// ALARMA: Cambio en el uso del sistema que no va a mejorar hasta que el usuario realice determinada accion
const ALARMA=["GENERAL"=>"","COMPRAS"=>"","PROVEEDOR"=>""];
// indicar mensaje a desplegar en configuracion/login.php


/*

'Estimados Proveedores y Socios comerciales:'
'Ha sido un placer para nosotros contar con su servicio durante este a&ntilde;o y por esta raz&oacute;n les expresamos nuestro m&aacute;s sincero agradecimiento.'
'Les informamos que por motivo del cierre fiscal de este a&ntilde;o recibiremos sus facturas con fecha del 2019 hasta el dia 31 de diciembre del 2019.'
'A partir del 1&deg; de enero del 2020 no se recibir&aacute;n facturas del a&ntilde;o 2019 en este portal.'
'Pedidos posteriores a esta fecha o que no hayan subido al portal por alguna situaci&oacute;n deber&aacute;n ser facturados con fecha de Enero del 2020.'
'Nos despedimos de ustedes no sin antes desearles una vez m&aacute;s Feliz Navidad y Pr&oacute;spero A&ntilde;o Nuevo 2020.'

*/